### ISSUE TITLE
If you receive this error, please visit the Animonculory discord and see the pins for the missing files. Thank you.

### ISSUE THREAD

**Issue by PcNm** [Para0x/Fahdon-A-Skyrim-Together-Experience#5] opened 2023-02-04 03:08 UTC
Edit: I just noticed the recently closed issues. Please don't close issues while they remain unresolved.
I could've found a solution earlier if you hadn't closed them.

```
############ Wabbajack log file - 2023-02-04 03:37:49.9803 ############
00:00:00.000 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 228980, Name = Steamworks Common Redistributables, Path = C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared }
00:00:00.000 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 489830, Name = The Elder Scrolls V: Skyrim Special Edition, Path = D:\SteamLibrary\steamapps\common\Skyrim Special Edition }
00:00:00.009 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1162721350, Name = The Elder Scrolls V: Skyrim Anniversary Upgrade, Path = D:\GAME\Skyrim Anniversary Edition }
00:00:00.009 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1711230643, Name = The Elder Scrolls V: Skyrim Special Edition, Path = D:\GAME\Skyrim Anniversary Edition }
00:00:00.009 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:\ProgramData\Origin\LocalContent does not exist!
00:00:00.240 [INFO] (Wabbajack.MainWindowVM) Assembly Location: 
00:00:00.240 [INFO] (Wabbajack.MainWindowVM) Process Location: D:\GAME\Wabbajack\3.0.6.2\Wabbajack.exe
00:00:00.242 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.0.6.2
00:00:00.343 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 3587b188e03f0bcb453f97c749f5b8bbccb39510
00:00:00.343 [INFO] (Wabbajack.MainWindow) Running in D:\GAME\Wabbajack\3.0.6.2
00:00:00.366 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.19044.0
00:00:00.366 [INFO] (Wabbajack.MainWindow) System settings - (31,9GB RAM) (43,8GB Page), Display: 2560 x 1440 (11,8GB VRAM - VideoMemorySizeMb=10240)
00:00:00.373 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:46.525 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
00:00:46.525 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:00:46.525 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:00:46.525 [INFO] (Wabbajack.InstallerVM) Preparing WabbajackCDNDownloader
00:00:46.525 [INFO] (Wabbajack.InstallerVM) Preparing MegaDownloader
00:00:46.829 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: Fahdon - A Skyrim Together Experience - 0.0.1.0
00:00:46.968 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Configuring Installer
00:00:46.968 [INFO] (Wabbajack.Installer.StandardInstaller) Configuring Processor
00:00:46.968 [INFO] (Wabbajack.Installer.StandardInstaller) Install Folder: D:\GAME\Fahdon
00:00:46.968 [INFO] (Wabbajack.Installer.StandardInstaller) Downloads Folder: D:\GAME\Fahdon\downloads
00:00:46.968 [INFO] (Wabbajack.Installer.StandardInstaller) Game Folder: D:\SteamLibrary\steamapps\common\Skyrim Special Edition
00:00:46.968 [INFO] (Wabbajack.Installer.StandardInstaller) Wabbajack Folder: D:\GAME\Wabbajack\3.0.6.2
00:00:46.968 [INFO] (Wabbajack.Installer.StandardInstaller) Optimizing ModList directives
00:00:47.438 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for files to delete
00:00:47.448 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Cleaning empty folders
00:00:47.651 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for unmodified files
00:00:47.702 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Updating ModList
00:00:47.702 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 153842 directives to 153842 required
00:00:47.720 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:47.720 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:47.720 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:47.735 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:47.735 [INFO] (Wabbajack.Installer.StandardInstaller) Found 2901 total files, 1230 matching filesize
00:00:47.787 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 1 archives
00:00:47.787 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:00:47.994 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:00:47.994 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
00:00:47.994 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 1 archives
00:00:47.994 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:00:47.994 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading enbseries_skyrimse_v0475.zip
00:00:48.121 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file enbseries_skyrimse_v0475.zip|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 83
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 121
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 140
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 397
00:00:48.121 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:48.121 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:48.121 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:48.121 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:48.132 [INFO] (Wabbajack.Installer.StandardInstaller) Found 2901 total files, 1230 matching filesize
00:00:48.167 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download enbseries_skyrimse_v0475.zip (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/enbseries_skyrimse_v0475.zip_1898e8aa-827b-4242-9a29-3094a8bbb98e/)
00:00:48.167 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives
```

**Describe the bug**
Installation fails to complete, thanks to a dead link, it would seem. (The enbSeries v.0475 is obsolete...)

**To Reproduce**
Run the Wabbajack installer and start the installation procedure with this modlist selected.

**Expected behavior**
I expected a successful installation of the modlist. (Other wabbajack modlists were tested, and they work.)
(Yes, I have both Steam & GOG versions, and they don't conflict.)

**Screenshots**
![image](https://user-images.githubusercontent.com/4698421/216743855-c8078ebd-3ab6-4370-8f62-9ee8e05a3374.png)
![image](https://user-images.githubusercontent.com/4698421/216743913-6e339682-9355-4a44-bf3a-2363c4f38304.png)

**Modlist version**
Whichever version is currently distributed through Wabbajack. See the log.

**Did you add any additional mods?**
Nope. Didn't even get a chance to do so.

Edit: The ugly solution was to create a temporary Discord account to access the missing file and download it to the mods downloads folder for Fahdon.

**Comment by Para0x** [comment] 2023-02-04 05:50
If you came to the discord server like I asked, you would see the pinned file. This is NOT a bug. It's an issue with the WJ CDN, due to a file accidentally being removed by another author. This changed the hash ID of the file, so every list with this file cannot resolve it. We've had to pin the link to it in the discord.

This won't be fixed until I can compile again, however the current version of WJ adds the entire list size to my drive as a temp download to cache everything on the new compiler, which I am currently unable to accommodate. It's a concession we have to make for the moment, so please come to the discord for support.

This is being marked as closed, it's not a bug with the list.

As stated in the readme, the support for the list is done on the discord server. While you can make issue requests, unless it is something that needs my direct intervention on this forum for some reason, I'll redirect you to the discord each time.

**Comment by Para0x** [comment] 2023-02-04 05:55
By the way, you can review closed issues, but I'll leave this opened in case other people can't find it.

**Comment by natemellendorf** [comment] 2023-02-12 20:21
Link to the pin: https://discord.com/channels/773659452392865792/1026149966021931028/1026361607657361492

**Comment by Althro** [comment] 2023-07-03 20:33
All being well, I should have a fixed version ready which will fix the download issues soon.

**Comment by Para0x** [comment] 2023-07-10 03:19
This has been updated, and should now be fixed.

**Closed as completed by Para0x** 2023-07-10 03:19 UTC
